default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  port: 5433
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: reval_development

test:
  <<: *default
  database: reval_test

production:
  <<: *default
  database: reval_production
